### ISSUE TITLE
能否支持 2021.3 版本的idea？

### ISSUE THREAD

**Issue by Markuna** [GuangYiDing/BeanUtilHelper#3]
另：期待能直接在对象属性上右键分析，找到所有get set 以及被 copyProperties 的地方

**Comment by GuangYiDing** [comment]
由于本项目使用了JDK 17 Record 以及 IDEA 的预览功能,经测试无法支持 2021.3 版本.

![image](https://github.com/GuangYiDing/BeanUtilHelper/assets/33063398/4b2d6e46-ca16-45a6-a8cc-97d499ed1910)

属性分析以及索引`copyProperties`将添加到开发计划中
